### ISSUE TITLE
Example out of date

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia-extension-example#3]
I am trying to rebuild this example with a current Theia clone using:

`yo theia-extensions myextensionname`

But I get stuck as the Theia libraries of this example seem to be out of date. For instance in the new Theia library there is no

```
@inject(FrontendApplication)
protected readonly app: FrontendApplication;
this.app.shell.addToMainArea(widget);
```

This call is made in the `markdown-preview-open-handler.ts` here in this example.

Is there an updated version to this example? How would I open a new widget area (basically a tab window) with the current Theia library version (current date: 2018-04-16)?

**Comment by spoenemann** [comment]
See #2 :-)

**Comment by jeanlucburot** [comment]
Thanks! ;)
