### ISSUE TITLE
Creating a Xtext DSL for Theia

### ISSUE THREAD

**Issue by SharkJ** [theia-ide/theia-extension-example#4]
Hi,
I need to add a language extension to Theia by implementing a DSL I created using Xtext. I found [this repo](https://github.com/theia-ide/theia-xtext) but I get so many errors when trying to build it (probably because it is outdated). Could you please tell me the steps to follow in order to implement my DSL to Theia?
Thanks!

**Comment by SharkJ** [comment]
Yes, it works well with Gitpod. But when I try to build it locally, I get errors that I've mentioned [here.](https://github.com/theia-ide/theia/issues/3564)

**Comment by svenefftinge** [comment]
https://github.com/theia-ide/theia-xtext/issues/8 has been merged. Please reopen if there is still something missing.
